### ISSUE TITLE
Épico: Administração de Ingressos

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/ticket-event#179]
Objetivo: Automatizar o processo de emissão, acesso e gestão de ingressos para eventos.
Principal Entrega: Sistema integrado de gestão de ingressos.
Critérios de Aceitação:
Geração automática de ingressos após a inscrição do participante.
Possibilidade dos participantes acessarem seus ingressos digitalmente.
Sistema de check-in eficiente usando os ingressos.

Histórias
- [ ] https://github.com/desenvolvendo-me/ticket-event/issues/29 
- [ ] https://github.com/desenvolvendo-me/ticket-event/issues/31
- [ ] https://github.com/desenvolvendo-me/ticket-event/issues/32
- [ ] https://github.com/desenvolvendo-me/ticket-event/issues/82
